stages:
  data_ingestion:
    cmd: python src/SportsImageClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/SportsImageClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data


  prepare_base_model:
    cmd: python src/SportsImageClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/SportsImageClassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
      - RANDOM_ROTATION_FACTOR
      - RANDOM_CONTRAST_FACTOR
      - RANDOM_TRANSLATION_WIDTH_FACTOR
      - RANDOM_TRANSLATION_HEIGHT_FACTOR
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/SportsImageClassifier/pipeline/stage_03_model_trainer.py
    deps:
      - src/SportsImageClassifier/pipeline/stage_03_model_trainer.py
      - config/config.yaml
      - artifacts/data_ingestion/data
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
    outs:
      - artifacts/training/model.keras


  evaluation:
    cmd: python src/SportsImageClassifier/pipeline/stage_04_model_evaluation_mlflow.py
    deps:
      - src/SportsImageClassifier/pipeline/stage_04_model_evaluation_mlflow.py
      - config/config.yaml
      - artifacts/data_ingestion/data
      - artifacts/training/model.keras
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false