IMAGE_SIZE: [256, 256, 3] 
BATCH_SIZE: 32
INCLUDE_TOP: False
EPOCHS: 2
CLASSES: 100
WEIGHTS: imagenet
LEARNING_RATE: 0.0001
RANDOM_ROTATION_FACTOR: 0.15
RANDOM_CONTRAST_FACTOR: 0.1
RANDOM_TRANSLATION_WIDTH_FACTOR: 0.1
RANDOM_TRANSLATION_HEIGHT_FACTOR: 0.1